version: "3"

services:

  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: SDL_namenode
    restart: unless-stopped
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./env/hadoop.env


  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: SDL_datanode
    restart: unless-stopped
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./env/hadoop.env

  
  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    container_name: SDL_resourcemanager
    restart: unless-stopped
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864"
    env_file:
      - ./env/hadoop.env


  nodemanager1:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    container_name: SDL_nodemanager
    restart: unless-stopped
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
    env_file:
      - ./env/hadoop.env


  historyserver:
    image: bde2020/hadoop-historyserver:2.0.0-hadoop3.2.1-java8
    container_name: SDL_historyserver
    restart: unless-stopped
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    env_file:
      - ./env/hadoop.env


  spot-app:
    # image: smartdatalake/scinem_app_01
    image: spot
    container_name: SDL_scinem_app
    environment:
      - _JAVA_OPTIONS=-Xmx1024m -Xms512m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=false
      - SPRING_DATA_MONGODB_URI=mongodb://spot-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=SpOT
      - JHIPSTER_SLEEP=31 # gives time for other services to boot before the application
      - spark_master=spark-master:7077
    ports:
      - 8181:8181
    volumes:
      - ./data/scinem/data:/data/SciNeM/SciNeM-data
      - ./data/scinem/results:/data/SciNeM/SciNeM-results
      - ./libs/SciNeM-workflows:/data/SciNeM/SciNeM-workflows


  spot-mongodb:
    image: mongo:4.0.13
    container_name: SDL_scinem_mongo_db
    ports:
      - '27018:27017'


volumes:
  hadoop_namenode:
  hadoop_datanode:
  hadoop_historyserver:

