version: "3"

services:

  spark-master:
    image: smartdatalake/spark-master:3.1.2-hadoop3.2
    container_name: SDL_spark-master
    ports:
      - "9080:8080"
      - "7077:7077"
    environment:
      - "SPARK_LOCAL_IP=spark-master"
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000

  spark-worker:
    image: smartdatalake/spark-worker:3.1.2-hadoop3.2
    container_name: SDL_spark-worker # Removev this for many
    depends_on:
      - spark-master
    ports:
      - "9081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SPARK_LOCAL_IP=spark-worker"
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    env_file: ./env/spark-worker.sh

volumes:
  hadoop_namenode:
  hadoop_datanode:
  hadoop_historyserver:
